### ISSUE TITLE
Moving ~/Openbazaar to ~/OpenBazaar2 and then relinking to it from ob.cfg breaks customisation (and potentially the listings).

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Server#198] opened 2016-02-05 16:23 UTC
I run the server, which creates ~/Openbazaar, then do some customisations like change the background image and change the avatar. 
I 'mv Openbazaar Openbazaar2'. Then I put DATA_FOLDER = /Users/daniel/OpenBazaar2/ in ob.cfg.
I run the client again and some customisations are lost. The colors remain but the pictures are lost. 

Last time I tried this (a few days ago) the listings were missing as well.

If I move the folder back to it's original location everything works again. This means that I can't create multiple shops and switch between then by changing the ob.cfg... 

I imagine that people running multiple stores would find this a huge problem.

**Comment by tcharding** [comment] 2016-02-06 09:57
Issue confirmed

**Comment by JustinDrake** [comment] 2016-02-15 23:44
+1 Multiple stores on the same computer is important for testing, crawlers, sellers, etc.

**Comment by cpacia** [comment] 2016-02-15 23:49
This is because the db saves an absolute path to those images. https://github.com/OpenBazaar/OpenBazaar-Server/blob/master/db/datastore.py#L42

If someone wants to submit a PR to change it to a path relative the datafolder that would fix it.

Also running multiple nodes does work if you set a new datafolder in the config before starting a new instance.

**Comment by ac225519** [comment] 2016-02-16 00:46
This should work:
Download my portable package: https://www.mediafire.com/folder/mpjxf3cocpof7/OpenBazaar_Test_LINUX_Builds
Unzip / unTar it.
cd OpenBazaar
cp -a OpenBazaar-Server OpenBazaar-Server_2
cp -a OpenBazaar-Server OpenBazaar-Server_3
(as much as you like)
cd OpenBazaar-Server
./start-openbazaar-node start --port=28467 --restapiport=18469 --heartbeatport=18470 --websocketport=18466
cd OpenBazaar-Server_2
./start-openbazaar-node start --port=27467 --restapiport=17469 --heartbeatport=17470 --websocketport=17466
cd OpenBazaar-Server_3
./start-openbazaar-node start --port=26467 --restapiport=16469 --heartbeatport=16470 --websocketport=16466
And so on...
You got the idea.
lsof -i -n -P
ob_python 6288 user    3u  IPv4 2151144      0t0  TCP 127.0.0.1:18470 (LISTEN)
ob_python 6288 user   16u  IPv4 2151322      0t0  UDP *:1024 
ob_python 6288 user   17u  IPv4 2151323      0t0  TCP 127.0.0.1:18466 (LISTEN)
ob_python 6288 user   19u  IPv4 2151324      0t0  TCP 127.0.0.1:18469 (LISTEN)
ob_python 6288 user   24u  IPv4 2151332      0t0  TCP 192.168.1.27:51334->168.235.82.149:9091 (ESTABLISHED)
ob_python 6288 user   27u  IPv4 2151331      0t0  TCP 192.168.1.27:34744->168.235.82.149:9092 (ESTABLISHED)
ob_python 6368 user    3u  IPv4 2153845      0t0  TCP 127.0.0.1:17470 (LISTEN)
ob_python 6407 user    3u  IPv4 2154420      0t0  TCP 127.0.0.1:16470
I'm not sure that the DHT has no bug and can deal with N instances with different ports on the same IP.
The  UDP *:1024  looks suspicious.
Chris ?

**Comment by tcharding** [comment] 2016-02-16 21:52
Following on from cpacia's comment, it looks like api/restapi.py would need to modify all calls to 

`HashMap().insert(DATA_FOLDER + "store/media")`

 to remove DATA_FOLDER. Then all calls to  

```
file_path = self.db.HashMap().get_file(request.args["id"][0])
with open(file_path, 'r') as filename:
```
changed to, for example:
```
file = self.db.HashMap().get_file(request.args["id"][0])
file_path = join(DATA_FOLDER, file)
with open(file_path, 'r') as filename:
```
grep and wc tell me there are 25 cases that need seeing to (in restapi.py) and one in markets/contracts.py. If you can confirm that you think this is a correct solution Chris I can do the patch.

**Comment by drwasho** [comment] 2016-03-01 01:48
@dsmurrell @cpacia is this still a problem, if so do we intend to fix it?

**Comment by drwasho** [comment] 2016-04-20 07:14
Fixed in the latest server commit.

**Closed by drwasho** 2016-04-20 07:14 UTC
Labels: enhancement

**Comment by dsmurrell** [comment] 2016-04-20 07:19
Nice! :D
