### ISSUE TITLE
Enable Buyer ratings if they win a disputed transaction

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Server#247] opened 2016-03-01 01:27 UTC
Buyers who have won a dispute transaction (i.e. not a refund) need to be able to leave a rating for the Vendor.

Client mirror: https://github.com/OpenBazaar/OpenBazaar-Client/issues/860

**Comment by jjeffryes** [comment] 2016-03-17 19:13
This is a duplicate of #271

**Closed by jjeffryes** 2016-03-17 19:13 UTC
Labels: v1 mainnet requirement
