### ISSUE TITLE
Data could not be retrieved [object Object]

### ISSUE THREAD

**Issue by gehlm** [OpenBazaar/OpenBazaar-Server#255] opened 2016-03-02 22:33 UTC
Brief Description: Click on "Order #5e94859f3f8e2d7f130d17da0baebc0df601f37e" displays error message, "Data could not be retrieved [object Object]".

Operating System (OS and version): Ubutnu 15.10
OpenBazaar version:  Version 1.0.6
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1.  Create "service" product
2. 
3. 

Observed Behavior:
Error dialog.

Expected Behavior:
Details of paid order. Should display ship to address, and a description of the "service"

Additional info (links, images, etc go here):

http://imgur.com/a/34TAu

**Comment by cpacia** [comment] 2016-03-02 23:16
I think this is somehow related to a failure in libbitcoin-client. If you can find a stack trace that would help.

**Comment by JustinDrake** [comment] 2016-03-03 00:13
Why are we using libbitcoin again? Why not use SPV nodes?

**Comment by cpacia** [comment] 2016-03-03 00:18
It might be able to do SPV. I wrote an (incomplete) SPV library. https://github.com/cpacia/pybitcoin

The issue is mainly that the moderator can't look up a transaction and get the inputs if it's SPV (since he doesn't learn of the funding tx until after it confirms). I suppose we could have either party to the dispute just send over the inputs and have the moderator just sign them without looking up the tx in the chain.

**Comment by cpacia** [comment] 2016-03-03 00:18
That's a lot of work though to make that library work 100%.

**Comment by JustinDrake** [comment] 2016-03-03 05:54
What's wrong with using an off-the-self SPV library (instead of starting from scratch)?

**Comment by drwasho** [comment] 2016-03-03 06:11
There aren't any good python ones AFAIK.

**Comment by JustinDrake** [comment] 2016-03-03 09:58
@drwasho Are we restricting ourselves to Python? Seems like a wasted opportunity.

**Comment by drwasho** [comment] 2016-03-03 11:47
We're already python based for the backend. But, show me a good alternative that is cross-platform? And don't suggest anything with Java.

**Comment by hoffmabc** [comment] 2016-03-03 12:28
We could wrap a c++ or Java version but kind of annoying if we are just turning around to use it with Python.

**Comment by JustinDrake** [comment] 2016-03-03 14:25
@drwasho: https://github.com/jgarzik/picocoin?

**Comment by cpacia** [comment] 2016-03-03 19:19
this should fixed now.

**Closed by cpacia** 2016-03-03 19:19 UTC
