### ISSUE TITLE
Store Color Costomization not propperly saved in settings

### ISSUE THREAD

**Issue by SimonBelmond** [OpenBazaar/OpenBazaar-Server#445] opened 2016-06-23 11:53 UTC
Brief Description: 

Operating System (OS and version): Ubuntu 14.04
OpenBazaar version: 1.1.6.deb
Hardware: 4gb ram, HP mini desktop (sorry for crappy description)

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Create a new store
2. Costomize the colors and image of your page and press save
3. Got to settings and change anything (not image or colors) and hit save

Observed Behavior:

Colors change back to default theme.

Expected Behavior:

Colors are saved in settings too

My Workaround:

Write down RGB codes and enter them in the settings page and hit save. This way they are in fact saved.

Additional info (links, images, etc go here): The bug is not 100% reproducible for the image but for the colors.

**Comment by jjeffryes** [comment] 2016-06-23 14:57
So far I haven't been able to reproduce this. 

If you use the top right menu to open the About modal, what version is the app?

In step 2, when you customize the page colors and save, are you doing this on your user page using the customize button?

If so, if immediately after changing the colors you navigate away from that page and then navigate back to it, is the page still using the custom colors you picked?

When you go to the settings page, are the colors of the page the custom colors you set in step 2?

On the Settings/Page tab, what are the values in the Primary Color, Secondary Color, Background Color, and Text Color fields?

Whatever is in those fields is what will be saved, if they don't match the colors you set in step 2, then either the colors aren't being saved, they can't be retrieved, or they've somehow been saved in the wrong format.

**Comment by jjeffryes** [comment] 2016-06-23 15:27
I've found the cause of this issue, and am moving it to the client repo.

**Comment by jjeffryes** [comment] 2016-06-23 15:27
Issue moved to [OpenBazaar/OpenBazaar-Client #1720](https://github.com/OpenBazaar/OpenBazaar-Client/issues/1720) via [**ZenHub**](https://www.zenhub.com/)

**Closed by jjeffryes** 2016-06-23 15:27 UTC

**Comment by SimonBelmond** [comment] 2016-06-23 19:08
Glad you could reproduce it. Initial color change was on my page not in settings. colors were showing correctly until I went and changed something else in the settings and hit save. then the settings were overwritten back to initial theme.
