### ISSUE TITLE
Periodic CPU hogging

### ISSUE THREAD

**Issue by grzegorz-kraszewski** [OpenBazaar/OpenBazaar-Server#336] opened 2016-04-06 19:29 UTC
Brief Description: The server loads a CPU core 100% for a few minutes periods. After about 10 hours of running, CPU is fully loaded almost constantly. During this time the server stops to respond to any connections. Finally one has to kill the 'python' process and restart the OB server.

Operating System (OS and version): Debian Linux 8.4
OpenBazaar version: Server 0.1
Hardware: Hyper-V virtual machine on 12-core Intel Xeon @ 2.6 GHz with one physical core and 8 GB RAM assigned to the VM.

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Run the server.
2. Observe CPU load.

Observed Behavior: Constant 100% CPU load in a few minutes periods, longer after OpenBazaar server is running for more than 10 hours. During these periods the server does not respond to a remote controlling client, also no P2P connections are accepted.

Expected Behavior: 

Additional info (links, images, etc go here):

**Comment by TheCookieLab** [comment] 2016-04-07 00:46
+1

Operating System (OS and version): Ubuntu 14.04.4 LTS
OpenBazaar version: Server 0.1
Hardware: Digital Ocean VPS 1 GB Memory / 30 GB Disk

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Run the server.
2. Observe CPU load.

Observed Behavior: After running for awhile (ex. overnight), I'm no longer able connect via the client unless the OB server is bounced. 

![ob](https://cloud.githubusercontent.com/assets/6332181/14337076/916c467c-fc38-11e5-9507-806c0b453d34.jpg)

**Comment by drwasho** [comment] 2016-04-07 00:49
Yep, working on it right now!

**Comment by KbI31K** [comment] 2016-04-07 21:38
The same was on 1.1.0 release  on raspberry pi. I had to restart pi to get connection. Python service load was 100%, no connection to the server.
Did 'git pull' command and updated server part a day ago.
Now is ok. 24 hours - works fine, connection is ok.

**Comment by lunokhod** [comment] 2016-04-13 07:56
I have the same problem with OSX (10.11.4). This is a critical bug for me as I can not leave my laptop server running non-stop at 100% cpu usage.

**Comment by Chafalleiro** [comment] 2016-04-13 10:07
Same on Debian 8 in plesk VPS

**Comment by drwasho** [comment] 2016-04-13 11:35
Some code was committed today to the server repo. Preliminary indications are that this problem is fixed with a bonus significant performance improvement.

**Comment by KbI31K** [comment] 2016-04-14 00:12
It works fine after update on raspberri pi 3.  no more 100% cpu load. Works faster fro sure. Thanks!

**Comment by drwasho** [comment] 2016-04-14 00:52
I'm gonna let my nodes run for the rest of the day. If they're fine, we should close this issue.

**Comment by Chafalleiro** [comment] 2016-04-14 11:27
Working fine after one day.

**Comment by hoffmabc** [comment] 2016-04-14 11:27
Same here

**Comment by lunokhod** [comment] 2016-04-14 12:24
No problems on OSX after 24 hours.

**Comment by drwasho** [comment] 2016-04-14 13:11
Ok. I'm closing this issue. Great job @cpacia

**Closed by drwasho** 2016-04-14 13:11 UTC
Labels: bug: reproducible
