### ISSUE TITLE
On close: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by moldcraft** [OpenBazaar/OpenBazaar-Server#249] opened 2016-03-02 09:05 UTC
Brief Description: 

Operating System (OS and version): Ubuntu 14.04
OpenBazaar version: 0.1.0
Hardware: PC

Reproducible: Always

Steps to reproduce:
1. Install openbazaar_1.0.6_amd64.deb
2. Start application
3. Close application

Observed Behavior:
On close I get in terminal

```
Closing Application
Shutting down server daemon
Segmentation fault (core dumped)
```

and sometimes Ubuntu shows an alert that the app was closed unexpected and ask me: reopen, leave closed.

Expected Behavior:
Close without error

Additional info (links, images, etc go here):
Screencast https://vid.me/aknh

**Comment by ac225519** [comment] 2016-03-04 01:42
Also Segmentation fault with Linux Mint LMDE2 Kernel 4.4.1-040401-lowlatency

**Comment by moldcraft** [comment] 2016-03-11 08:58
[More details](https://static.md/4319a2b0-e767-11e5-bc17-ef4999aefd3f)

**Comment by ericfont** [comment] 2016-04-05 01:11
I can confirm this segfault when close, using 1.1.0 x86-64 release on a fresh live Ubuntu 14.04.4-desktop iso in qemu (nothing else installed before installing OpenBazaar .deb via Ubuntu Software Center).  Attached is the apport crash file found in /var/crash: 
[openbazaar.999.crash.zip](https://github.com/OpenBazaar/OpenBazaar-Server/files/203609/openbazaar.999.crash.zip)

The only final console output is: <pre>Closing Application
Shutting down server daemon
Segmentation fault (core dumped)</pre>

**Comment by ericfont** [comment] 2016-04-05 01:49
I ran gdb and attached to the two openbazaard process, one which received a SIGPIPE: https://gist.github.com/ericfont/74cb26a5d172e24738d17953371eeaae and another which just received a regular SIGTERM: https://gist.github.com/ericfont/9378ca4e6df7242308a30b61b701230e

I think these lines are telling us that the crash is due to SIGPIPE:<pre>Program received signal SIGPIPE, Broken pipe.
0x00007fa5840a788d in write () at ../sysdeps/unix/syscall-template.S:81
81	../sysdeps/unix/syscall-template.S: No such file or directory.</pre>

Wikipedia says "The SIGPIPE signal is sent to a process when it attempts to write to a pipe without a process connected to the other end."

**Comment by ericfont** [comment] 2016-04-05 02:10
I should note that those two gists above are from the daemon.  I should note that I saw two openbazzard processes, which is why I attached to both, but I'm wondering now if one of those daemons was from a prior execution.  

Anyway, I did gdb again, this time on the pid of the lowest numbered openbazaar process that appeared (after I executed openbazaar in another terminal) and which is the process that gets the SIGSEGV (Segmentation Fault) upon exit: https://gist.github.com/ericfont/b8069ba92c3c958dd32caab51b94e578#file-gdb-attached-to-openbazar-L294-L295

**Closed** 2016-04-15 18:03 UTC
Labels: bug: please confirm

**Comment by ericfont** [comment] 2016-04-15 20:12
Why close this issue?

**Comment by hoffmabc** [comment] 2016-04-15 20:15
Latest version should resolve this issue.
